### ISSUE TITLE
Connectivity Error: The Fourth connection is fail.

### ISSUE THREAD

**Issue by yairbb** [QualiSystems/OpenStack-Shell#137]
STR: 

1) Have a reservation with Deployed App.
2) Connect CVC to 4 vlan.
3)  trigger "connect" command to all the vlans one by one.

BIR:

All the connection shall be succeeded.
Actually: from the Fourth " connection failed" is obtained.

**Comment by yairbb** [comment]
the bug is in OpenStack not in the server.

**Comment by yairbb** [comment]
![image](https://cloud.githubusercontent.com/assets/20166257/22428806/1c4d75a4-e711-11e6-83d8-b5efde092fd9.png)

**Comment by yairbb** [comment]
@gabhijit-izel 
logs will be sent to you by mail.

**Comment by gabhijit-izel** [comment]
Shouldn't VLAN ID 4096 fail? The error reported is incorrect and correct Exception should be reported. Is that the expected behavior? 4096 is out of Maximum VLAN range. I think 4096 failed is correct - but the error should be correct one and not the one that we are getting - that is "list index out of range"

**Comment by GilGald** [comment]
@gabhijit-izel 
note that Its VXLAN not VLAN

**Comment by yairbb** [comment]
Yes .

As Gil wrote it is vxlan.

**Comment by gabhijit-izel** [comment]
Sorry - Got it - My bad - have to check the actual error that gets thrown in the openstack log.

**Comment by yairbb** [comment]
fixed!
