### ISSUE TITLE
Requested vNic Name support

### ISSUE THREAD

**Issue by alexazarh** [QualiSystems/OpenStack-Shell#143]
A user might want to assign a Nic name from the UI to attach to a specific VLAN. In connectivity request if "Vnic Name" is available, we should attach an interface with same number to a particular VLAN.

**Comment by gabhijit-izel** [comment]
In general, Openstack (rather KVM) interfaces typically get the names in order starting with 'eth0' - Since we use 'eth0' for management network, for connectivity networks - we have interface names starting from eth1 so on. 

Let's say in a connectivity request we get following interfaces "vnic name:1" and "vnic name:3" , we would associate those with eth1 and eth3 respectively - but for this to work in openstack a dummy interface needs to be generated and attached to a holding network. This can be achieved as follows  - we create three interfaces eth1, eth2 and eth3 -- eth1 / eth3 would be attached to respective VLANs in the connectivity request, eth2 will be attached to a dummy holding network - 

If - new interface is added during running a reservation - we first detach eth2 (connected to a dummy network - and then attach back again to new VLAN). Verified - detaching and attaching back an interface - generates the lowest name - so eth2 will be deleted and added back again).

**Comment by gabhijit-izel** [comment]
Added a very high level POC code in branch `feature/gabhijit-izel_143_vnic_names_poc_code`
