### ISSUE TITLE
floating IP using poolslazy

### ISSUE THREAD

**Issue by gabhijit-izel** [QualiSystems/OpenStack-Shell#149]
When we are creating a floating IP, right now the actual subnet on which floating IP is to be created is not used. Consequently if more than one subnets are attached to the same "external" network, one of them will be created at random. This might be actually a problem - if we want to use a specific IP Pool and/or Subnet. We should be able to choose the subnet for which we want to create a floating IP

**Comment by TomerAdmon** [comment]
As a admin/user I would like to be able to choose a floating IP subnet instead of choosing an external network Id on the the cloud provider and on the app level.  The input should be the UUID of the subnet from which we would get an gloating IP.

The input should be validated during the OpenStack resource autoload, and throw an exception if not exists.

An app deployment should also throw an exception if the subnet doesn't exist.

The floating IP of the VM should be an IP form within the subnet.

Please see updated version in confluence of here:
[QP-33652772-130217-0915-3.pdf](https://github.com/QualiSystems/OpenStack-Shell/files/770541/QP-33652772-130217-0915-3.pdf)

**Comment by yairbb** [comment]
[Test Plan](http://team:8080/tfs/Quali-Collection/QualiSystems/_testManagement?planId=125053&suiteId=159486&_a=tests)

**Comment by Shnitselon** [comment]
documented the following:

For the deployment type:
====
Add Floating IP: Set to True to use a static (public) IP address to communicate with the instance from outside the virtual network. Default value is False.
In most cases the floating IP address is associated with the instance until the instance is stopped or terminated, after which the floating IP is  no longer available. You can reserve a floating IP in OpenStack to ensure that the IP is available to your subscription at any time.

Floating IP Subnet Id attribute: UUID of the subnet that will allocate floating IDs to the OpenStack instances.
Leave empty to use the default external network ID specified in the OpenStack resource.
====

For the cloud provider resource:
====
Floating IP Subnet Id attribute: UUID of the subnet that will allocate floating IDs to the OpenStack instances.
====
