### ISSUE TITLE
Nic is not recognized by the VM (udev rules)

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/OpenStack-Shell#159]
STR:
1) deploy an P2P scenario with CentOS machines
2) ssh into one of the machines and execute ifconfig -a

result:
the Vlan network is not configured as nic on the machine

this is probably since the machine should be restarted or NICs should be refrashed after an nix is added to a machine from the OpenStack AIP or from horizon.

the main problem here is that a user is usual to deploy machines with few networks form Horizon and all the networks will be configured since they attached when the machine is created. When a machine is configured form CloudShell, the machine will be powered on first and then connectivity process will attach a NIC but nothing refresh the NIC's on the VM to update the connectivity on the OS level.

**Comment by alexazarh** [comment]
Conclusions:
* We would like to add an attribute called "Auto udev" that will be a user input and will be true by default on the app.  The attribute description will be "Configure Linux udev rules to allow new interfaces to be recognized by the OS automatically. When using Windows machines this attribute should be set to false."

* App that will have this the "Auto udev" attribute set to True will execute a user-data script during the deployment that refreshes the udev rules so new interfaces that were added in the Sandbox will be added in the OS level.

* We need documentation for the user-data script we are executing

Concern: What will happen if this user-data script will be executed on Windows machines?

**Comment by yairbb** [comment]
Test Plan

**Comment by yairbb** [comment]
[Test Plan](http://team:8080/tfs/Quali-Collection/QualiSystems/_testManagement?planId=125053&suiteId=159479&_a=tests)

**Comment by TomerAdmon** [comment]
@yairbb - 
- Please add test case regarding Windows VM, case about Ubuntu VM. Have clear seperation between connectivity in Setup to connectivity in active Sandbox.
- Did you reviewed the documentation? do you think the information there is enough?
- What about scenario where the OS is not supporting udev? the user will see error? the Setup will fail?
- What if there is no cloud-init installed on the machine?

**Comment by yairbb** [comment]
@TomerAdmon 

Pls provide the expected behavior in the third and forth points you mentioned.

what about the concern alex mentioned above :"Concern: What will happen if this user-data script will be executed on Windows machines?" what shall be the behavior here too ?

I will implement the other points you have commented.

**Comment by alexazarh** [comment]
@yairbb - about windows, the way it is implemented it should be ignored. It means if the Auto dev attribute is set to True for a Windows app nothing should happen and the deploy will ignore it...

**Comment by gabhijit-izel** [comment]
Re-opening!! We are using python2 to update udev rules and Ubuntu 16.04 cloud image - by default does not support Python2, argh!!!!. So we should basically use a simple bash script to add udev rules and not use Python. This will need to be tested in Windows separately

**Comment by gabhijit-izel** [comment]
Right now I have managed to figure out udev rules that works for CentOS and Ubuntu 16.04.  However I am not very sure whether this is ideal. For example there are a number of 'distribution specific things' we already are doing. The way to solve this problem eventually would be to have an App attribute called OS Flavor (Drop Down)  - and then we should basically try to have "udev rules and other configs" tested for these flavors added. Trying a very 'generic' solution - is probably not the best way to go about it. 

or Alternatively We should have this as a FreeText attribute and allow people to go about writing udev rules themselves (which in a way is good as well - because that gives them finer control over how they want to do it).
