### ISSUE TITLE
Assigning Floating IP to an Instance

### ISSUE THREAD

**Issue by gabhijit-izel** [QualiSystems/OpenStack-Shell#17]
In order to connect to OpenStack Instances, from an external network (or Internet), it should be possible to reach these instances from outside. The way it is typically achieved is - a floating IP is assigned to the instance while the instance is present and then this IP can be recycled later. Most of the IP management is taken care off by Openstack. Openstack Also provides APIs to assign floating IPs to instances, so we should have support to - 
- [ ] Add floating IP to Instance:

**Comment by gabhijit-izel** [comment]
Moved this to comment - since we might have 2 different people assigning the same IP addresse from 2 different reservations, we are going to change this attribute behavior in 7.2 for AWS, and Openstack should also adopt the same logic. this should become a boolean instead of an IP address string attribute. see https://github.com/QualiSystems/AWS-Shell/issues/250 for more details.

**Comment by TomerAdmon** [comment]
As a user i would like to be able to get a Floating IP for an instance in Sandbox. in order to do so, i would like to choose "Floating IP = True" on the app and that the deployment of the app will end with the floating IP in the "Public IP" attribute on the deployed app.
In order to choose the correct network for the floating IP, the admin of the system will be requested to fill another attribute on the cloud provider resource (in the "create new resource" phase) that will get UUID of the default network to use for getting a floating IP.
App developer will then be able to override the "default floating IP network" on the app level to allow flexibility on the app level.
deleting the app will detach the IP from the machine.
The "External Network Id" attribute value will be taken from the cloud provider if empty on the app.

Attributes: 
On the app:
Name: "Add Floating IP" 
Type: Boolean
Description:  Use a floating IP to set a static IP using Neutron L3 agent and not using a DHCP service. Floating IP is commonly used for accessing a machine from public networks while private IP will be used by other instances in the same private networks.
 
On the cloud provider & On the app:
Name: External Network Id
Type: String
Description:  The UUID of the External Network to use for Floating IPs.
this attribute is a user input on the cloud provider and not a user input on the app.

Also documented in the OpenStack confluence page

**Comment by TomerAdmon** [comment]
@gabhijit-izel  - Please check how much effort it will be to add an option to override the "Default Security Group Id" also on the app level.

**Comment by TomerAdmon** [comment]
@gabhijit-izel  - We would like to know if a floating IP behaves as a static or dynamic ip and if there is a way in OpenStack to control this behavior. If there is, we would like to add an attribute that will control that.

**Comment by yairbb** [comment]
(Test Plan)[http://team:8080/tfs/Quali-Collection/QualiSystems/_testmanagement?planId=125053&suiteId=159195&_a=tests]
