### ISSUE TITLE
Teardown not clear the machine.

### ISSUE THREAD

**Issue by yairbb** [QualiSystems/OpenStack-Shell#183]
STR:
1) have a reservation with Deployed App Duration of the reservation short.

BIR:

After the teardown finished the VM is still valid in both cloudshell and openstack portal.

**Comment by yairbb** [comment]
![capture](https://cloud.githubusercontent.com/assets/20166257/23012486/286246b4-f42f-11e6-8be7-147ff521954f.PNG)

**Comment by yairbb** [comment]
logs:

[QsPortalIisExpressWatchDog.txt](https://github.com/QualiSystems/OpenStack-Shell/files/779391/QsPortalIisExpressWatchDog.txt)

[TeamServer.Service.txt](https://github.com/QualiSystems/OpenStack-Shell/files/779390/TeamServer.Service.txt)
[DisPro.txt](https://github.com/QualiSystems/OpenStack-Shell/files/779392/DisPro.txt)

**Comment by gabhijit-izel** [comment]
@yairbb : This error might be due to the following email - I sent out yesterday. The "floating IP" assigned was blocking everyone (it was a configuration error, it's fixed now). Looks like the affected instance is yours. 

--- email ---
A weird thing had happend a while back - one of the instances that got deployed OpenStackCentos-724ed7d8 had got a floating IP of 192.168.170.3 - consequently - from the BDT-EX one could not connect to 192.168.170.3 - This problem is fixed now - by disassociating the floating IP for that instance.

This is a configuration issue - that I am fixing by changing the subnet allocation range to start from 192.168.170.10 to be safe..... Just FYI
--- end email ---

**Comment by alexazarh** [comment]
@yairbb I cannot reproduce this. Please make sure you have the latest package.

**Comment by yairbb** [comment]
fixed!
