### ISSUE TITLE
refresh_ip story

### ISSUE THREAD

**Issue by gabhijit-izel** [QualiSystems/OpenStack-Shell#28]
Make this a story related #12

**Comment by yairbb** [comment]
Pls write specific story for refresh IP. 

Currently : not final 

(Test Plan)[http://team:8080/tfs/Quali-Collection/QualiSystems/_testManagement#planId=125053&suiteId=156307]

**Comment by yairbb** [comment]
Update the resource address with the private IP on network NIC that is associated with mgmt network

**Comment by yairbb** [comment]
@gabhijit-izel 

is this story already implemented ?

**Comment by gabhijit-izel** [comment]
Write in details: about refresh IP command !!

**Comment by TomerAdmon** [comment]
After a VM is deployed and powered On a "Refresh IP" command can be called to get back its IP and present it to the user and the deployed app's address.

This command should be called as part of the App Deploy, after some delay time once the VM is powered on

The "Refresh IP Timeout" attribute(not a user input) should be attached to the deployment option and to limit the refresh ip command execution. the default value is 600 and the description is "Timeout for waiting when obaining IP address (in seconds)" - exactly the same as we have in Vcenter.

since we are using a "mgmt netowrk" concept, we are not going to implement the "IP Regex" as we did in Vcenter.

**Comment by yairbb** [comment]
@TomerAdmon 

"This command should be called as part of the App Deploy" 

It was decided to omit this command from Setup in order to optimize the deployment process. 
Pls comment if you think there is place to have it anyway.

**Comment by yairbb** [comment]
@TomerAdmon 

shell refresh ip update the floating ip too ?
