### ISSUE TITLE
Installation Guide for management network

### ISSUE THREAD

**Issue by alexazarh** [QualiSystems/OpenStack-Shell#40]

**Comment by gabhijit-izel** [comment]
Management network for QualiX and Execution Server - 

1. A new network in OpenStack should be created that will be used as management network and a subnet should be assigned for this network.
2. It should be noted that this network should not be "external" (There is no implementation limitation of this network being external - however, every instance will have a network port on the management network.) 
3. The network created should have 'shared' flag set to True. Since this network will be shared by instances (that are deployed across different reservations and potentially different tenants/projects, this network should be shared. ie. the 'shared' flag should be set to True.
4. QualiX server should have a floating IP so that it can be accessed from external network.

**Comment by Shnitselon** [comment]
documented in the "OpenStack Configuration Requirements" topic of the online help

@TomerAdmon @gabhijit-izel
