### ISSUE TITLE
_get_unused_cidr should support 2nd octet as well

### ISSUE THREAD

**Issue by alexazarh** [QualiSystems/OpenStack-Shell#75]
Right now even for 10/ we are using only /24 we should also be using octet 2 so we can have many subnets like that

**Comment by gabhijit-izel** [comment]
For connectivity - we are using /24 networks. So we should be able to support all networks from 10.0.0.0/8 range - Right now we are only supporting networks from 10.0.0.0/16 Range. A real fix should support networks such as 10.0.0.0/16, 10.1.0.0/16 and so on and then a /24 network can be obtained with a base as one of the /16 network.

for instance currently if we have 10.0.0.0/16 - a reserved network - For connectivity we should get networks like - 

10.1.0.0/16 and so on.

One thing to keep in mind while testing - Use a *new* VLAN ID for this testing (and manual VLAN). Because Auto VLAN could use an already existing network.

**Comment by yairbb** [comment]
fixed!
