### ISSUE TITLE
Limitations document

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/OpenStack-Shell#92]
we whould like to deliver a document that will describe exactly what we are supporting and what are the limitations of the OpenStack-Shell

**Comment by gabhijit-izel** [comment]
API versions
-----------------
Nova API - Version 2 (tested and used features of base v2.0 - additional features supported by sub-releases 2.X are not used)
Neutron API - Version 2
Keystone API - Version 3

OpenStack Networking Model 
--------------------------------------------
OpenStack networking is not a Pure L2 model where - ports are attached to switches and VLANs. This is more of a L2/L3 hybrid where each L2 network (broadcast domain) also has got an L3 Subnet associated with it. We have implemented this model with using segmentation ID as VLAN or VxLAN. 

Access/Trunk VLANs
--------------------------------
Also - currently only  Access mode is supported that is end hosts are not VLAN aware.  VLAN trunking support is not present right now.

Attach VLAN to vNic
-----------------------------
Support for choosing VLAN to attach to a vNic does not exist right now due to hybrid L2/L3 model. 

VM Access using KeyPairs
-----------------------------------
Currently VM access is supported only using Username and Password. Key pairs are not supported right now.

Hotplug Interfaces 
-----------------------------
For automatically detecting interfaces on the deployed VMs - we use "Udev rules" - udev support should be present in the VM image for this (most of the standard cloud images have this support)

App Network CIDRs
-----------------------------
In the implementation we support /24 CIDRs right now. This might limit number of hosts that are supported on a Subnet to 255. 


Affinity Groups
----------------------
To support deployment of 'all' VMs of an App to same hypervisor, affinity groups with policy 'affinity' are used.

**Comment by Shnitselon** [comment]
Added topic "OpenStack Known Limitations" to online help

**Comment by Shnitselon** [comment]
@TomerAdmon @gabhijit-izel

**Comment by gabhijit-izel** [comment]
@Shnitselon : Following section needs further update - 

Hotplug Interfaces
----------------------------

For automatically detecting interfaces on the deployed VMs - we use "Udev rules" - udev support should be present in the VM image for this (most of the standard cloud images have this support). Also the image should have 'cloud-init' installed and enabled. Userdata feature of OpenStack to provide udev rules, that are installed by cloud-init.
